# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spartano
email: valdenio@spartan.digital
description: "O blog do guerreiro Spartano, treinamentos e dicas sobre tecnologia"
baseurl: "/blog" 
url: "http://spartan.digital" 
twitter_username: valdeniofreitas
github_username:  valdeniofreitas

# Build settings
markdown: kramdown
permalink: /:title
